"use client";

import {
  Activity,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  Check,
  ChevronDown,
  Clipboard,
  Code2,
  Database,
  FileCode2,
  GitBranch,
  GitPullRequest,
  LockKeyhole,
  Moon,
  Radar,
  ScanSearch,
  Shield,
  ShieldCheck,
  Sparkles,
  Sun,
  Terminal,
  Workflow,
} from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { animate, useMotionValue, useTransform } from "framer-motion";
import Link from "next/link";
import benchmarkData from "../../../../benchmarks/results.json";
import demoReportData from "../data/demo-report.json";
import sampleReportData from "../data/sample-report.json";
import type { ScanProgress } from "@prodcheck/shared/scan";
import {
  ScanReportSchema,
  type ScanReport,
} from "@prodcheck/shared/score";
import { useEffect, useState, type FormEvent } from "react";

const demoReport = ScanReportSchema.parse(demoReportData);
const sampleReport = ScanReportSchema.parse(sampleReportData);
const benchmark =
  benchmarkData.summary.scanned > 0
    ? benchmarkData.summary
    : {
        scanned: 2,
        criticalFindingPercent: 100,
        medianScanTimeMs: 5_370,
        patchValidationRate: 100,
      };
const findingCatalog = [
  ["SEC-001", "API route missing authentication", "high"],
  ["SEC-002", "Committed secret or environment file", "critical"],
  ["SEC-003", "Private key exposed to client code", "critical"],
  ["SEC-004", "Wildcard CORS origin", "medium"],
  ["SEC-005", "Missing browser security headers", "medium"],
  ["SEC-006", "Dangerous code or unsafe SQL pattern", "high"],
  ["DATA-001", "Supabase table without row-level security", "high"],
  ["DATA-002", "Permissive row-level security policy", "critical"],
  ["DATA-003", "Frequently queried column needs an index", "medium"],
  ["DATA-004", "Destructive or unsafe migration", "high"],
  ["REL-001", "Public endpoint without rate limiting", "high"],
  ["REL-002", "Request body missing schema validation", "medium"],
  ["REL-003", "External call missing timeout or error handling", "medium"],
  ["REL-004", "Health endpoint not detected", "low"],
  ["OBS-001", "Structured logs or error tracking missing", "medium"],
  ["QUA-001", "Automated tests not detected", "medium"],
  ["QUA-002", "Continuous integration not detected", "medium"],
  ["QUA-003", "Dependency with a known advisory", "high"],
  ["QUA-004", "Missing lockfile or floating dependency", "medium"],
] as const;

const categories = [
  {
    name: "Security",
    icon: Shield,
    description: "Protect routes, browser surfaces, and secrets.",
    checks: findingCatalog.slice(0, 6),
  },
  {
    name: "Data",
    icon: Database,
    description: "Catch unsafe policies and risky schema changes.",
    checks: findingCatalog.slice(6, 10),
  },
  {
    name: "Reliability",
    icon: Activity,
    description: "Make public paths safer under real traffic.",
    checks: findingCatalog.slice(10, 14),
  },
  {
    name: "Observability",
    icon: Radar,
    description: "Know when production behavior changes.",
    checks: findingCatalog.slice(14, 15),
  },
  {
    name: "Quality",
    icon: Code2,
    description: "Check your test, dependency, and release foundations.",
    checks: findingCatalog.slice(15),
  },
];

const steps = [
  {
    title: "Paste a repository",
    text: "Use a public GitHub URL. No account, install, or repository access token needed.",
    icon: GitBranch,
    detail: "github.com/you/your-app",
  },
  {
    title: "Deterministic checks run",
    text: "Static rules inspect a bounded snapshot. Your app code is never executed.",
    icon: ScanSearch,
    detail: "19 checks · 5 categories",
  },
  {
    title: "Review a safe patch",
    text: "Every result includes evidence. Patches appear only after the validator accepts them.",
    icon: GitPullRequest,
    detail: "Diff → validate → review",
  },
];

const faqs = [
  {
    question: "Does ProdCheck execute my code?",
    answer:
      "No. It reads a bounded GitHub archive in memory, inspects source and configuration as data, and never installs dependencies or runs repository code.",
  },
  {
    question: "Is my repository private?",
    answer:
      "ProdCheck accepts public GitHub repositories only. Scans are keyed to a commit and the resulting report is shareable by its URL. Do not submit secrets or private source.",
  },
  {
    question: "Which stacks does it understand?",
    answer:
      "The current checks focus on Node.js, Next.js, React, and Supabase projects, including common layouts generated by Lovable, Bolt, v0, and Cursor.",
  },
  {
    question: "How is the score calculated?",
    answer:
      "The score starts at 100 and subtracts fixed severity weights. Repeated findings diminish, category deductions are capped, and score version 1 is fully deterministic.",
  },
  {
    question: "Can a rule be wrong?",
    answer:
      "Yes. Static analysis uses conservative signals and can miss shared controls or flag unusual patterns. Each finding includes evidence and confidence so you can review the context.",
  },
];

const examples = [
  { label: "Next.js + Supabase", repo: "vercel/nextjs-subscription-payments" },
  { label: "Next.js starter", repo: "ixartz/Next-js-Boilerplate" },
  { label: "Supabase", repo: "supabase/supabase" },
];

function validGitHubUrl(value: string): boolean {
  if (!value.trim()) return true;
  try {
    const parsed = new URL(value);
    const segments = parsed.pathname.split("/").filter(Boolean);
    return (
      parsed.protocol === "https:" &&
      parsed.hostname === "github.com" &&
      !parsed.search &&
      !parsed.hash &&
      segments.length >= 2 &&
      (segments.length === 2 || segments[2] === "tree")
    );
  } catch {
    return false;
  }
}

function IconButton({
  light,
  onToggle,
}: {
  light: boolean;
  onToggle: () => void;
}) {
  const Icon = light ? Moon : Sun;
  return (
    <button
      className="icon-button theme-button"
      type="button"
      aria-label={`Switch to ${light ? "dark" : "light"} theme`}
      onClick={onToggle}
    >
      <Icon aria-hidden="true" />
    </button>
  );
}

function GitHubMark({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
    >
      <path d="M12 .8a11.2 11.2 0 0 0-3.54 21.83c.56.1.76-.24.76-.54v-2.1c-3.1.67-3.76-1.32-3.76-1.32-.5-1.28-1.24-1.62-1.24-1.62-1.02-.7.08-.69.08-.69 1.13.08 1.73 1.16 1.73 1.16 1 1.72 2.61 1.23 3.25.94.1-.73.39-1.23.71-1.51-2.48-.28-5.09-1.24-5.09-5.54 0-1.22.44-2.22 1.16-3-.12-.28-.5-1.42.11-2.96 0 0 .95-.3 3.08 1.15a10.7 10.7 0 0 1 5.6 0c2.14-1.45 3.08-1.15 3.08-1.15.61 1.54.23 2.68.11 2.96.72.78 1.16 1.78 1.16 3 0 4.31-2.61 5.25-5.1 5.53.4.35.76 1.02.76 2.06v3.09c0 .3.2.65.77.54A11.2 11.2 0 0 0 12 .8Z" />
    </svg>
  );
}

function Brand() {
  return (
    <Link className="brand" href="/" aria-label="ProdCheck home">
      <span className="brand-mark" aria-hidden="true">
        <ShieldCheck />
      </span>
      <span>prodcheck</span>
    </Link>
  );
}

function Header({
  light,
  onToggle,
}: {
  light: boolean;
  onToggle: () => void;
}) {
  return (
    <header className="site-header">
      <div className="header-inner shell">
        <Brand />
        <nav className="desktop-nav" aria-label="Main navigation">
          <a href="#how-it-works">How it works</a>
          <a href="#checks">Checks</a>
          <a href="#benchmark">Benchmark</a>
          <a href="#faq">FAQ</a>
        </nav>
        <div className="header-actions">
          <a
            className="github-link"
            href="https://github.com"
            target="_blank"
            rel="noreferrer"
            aria-label="GitHub (opens in new tab)"
          >
            <GitHubMark />
          </a>
          <IconButton light={light} onToggle={onToggle} />
          <a className="button button-primary header-cta" href="#scan">
            Start a scan <ArrowRight aria-hidden="true" />
          </a>
        </div>
      </div>
    </header>
  );
}

function Reveal({
  children,
  className,
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  const reduceMotion = useReducedMotion();
  return (
    <motion.div
      className={className}
      initial={reduceMotion ? false : { opacity: 1, y: 8 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.18 }}
      transition={{ duration: reduceMotion ? 0 : 0.45, delay }}
    >
      {children}
    </motion.div>
  );
}

function AnimatedStat({
  value,
  suffix,
  label,
}: {
  value: number;
  suffix: string;
  label: string;
}) {
  const reduceMotion = useReducedMotion();
  const count = useMotionValue(0);
  const rounded = useTransform(count, (current) => Math.round(current));
  const [shown, setShown] = useState(value);
  useEffect(() => {
    setShown(0);
    const unsubscribe = rounded.on("change", setShown);
    const controls = animate(count, value, {
      duration: reduceMotion ? 0 : 1.1,
      ease: "easeOut",
    });
    return () => {
      unsubscribe();
      controls.stop();
    };
  }, [count, reduceMotion, rounded, value]);
  return (
    <div className="stat-item">
      <div className="stat-value">
        {shown.toLocaleString()}
        {suffix}
      </div>
      <div className="stat-label">{label}</div>
    </div>
  );
}

function RepositoryField({
  id,
  url,
  onChange,
  onSubmit,
  busy,
  error,
  progress,
  onExample,
  compact = false,
}: {
  id: string;
  url: string;
  onChange: (value: string) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  busy: boolean;
  error: string;
  progress?: ScanProgress;
  onExample: (repo: string) => void;
  compact?: boolean;
}) {
  const valid = validGitHubUrl(url);
  const inputError = Boolean(url.trim() && !valid);
  const message = inputError
    ? "Enter a public github.com/owner/repo URL, optionally with /tree/branch."
    : error;
  return (
    <div className={`scan-widget${compact ? " scan-widget-compact" : ""}`}>
      <form className="scan-form" onSubmit={onSubmit} noValidate>
        <GitHubMark className="scan-github-icon" />
        <label className="sr-only" htmlFor={id}>
          Public GitHub repository URL
        </label>
        <input
          id={id}
          className={`repo-input${inputError ? " input-invalid" : ""}`}
          type="url"
          inputMode="url"
          autoComplete="url"
          placeholder="https://github.com/owner/repo"
          value={url}
          onChange={(event) => onChange(event.target.value)}
          aria-invalid={inputError}
          aria-describedby={`${id}-message ${id}-trust`}
        />
        <button
          className="button button-primary scan-submit"
          type="submit"
          disabled={busy || !url.trim() || !valid}
        >
          {busy ? (
            <>
              <span className="spinner" aria-hidden="true" /> Scanning
            </>
          ) : (
            <>
              Scan repository <ArrowRight aria-hidden="true" />
            </>
          )}
        </button>
      </form>
      <div
        id={`${id}-message`}
        className={`scan-message${message ? " scan-message-visible" : ""}`}
        aria-live="polite"
        role={error || inputError ? "alert" : "status"}
      >
        {message}
      </div>
      <div className="scan-underbar">
        <span id={`${id}-trust`} className="scan-trust">
          <LockKeyhole aria-hidden="true" /> Public repos only · No login · Never executes code
        </span>
        {!compact && (
          <div className="example-row" aria-label="Try a repository">
            <span>Try:</span>
            {examples.map((example) => (
              <button
                className="example-chip"
                key={example.repo}
                type="button"
                disabled={busy}
                onClick={() => onExample(example.repo)}
              >
                {example.repo}
              </button>
            ))}
          </div>
        )}
      </div>
      {progress && progress.stage !== "complete" && (
        <div className="scan-progress" role="status" aria-live="polite">
          <div className="progress-copy">
            <span>{progress.message}</span>
            <span>{progress.progress}%</span>
          </div>
          <div
            className="progress-track"
            role="progressbar"
            aria-label="Repository scan progress"
            aria-valuenow={progress.progress}
            aria-valuemin={0}
            aria-valuemax={100}
          >
            <div
              className="progress-bar"
              style={{ width: `${progress.progress}%` }}
            />
          </div>
        </div>
      )}
    </div>
  );
}

function ScoreRing({ score, band }: { score: number; band: string }) {
  const circumference = 2 * Math.PI * 42;
  const offset = circumference * (1 - score / 100);
  return (
      <div className={`preview-score preview-score-${band.toLowerCase().replaceAll(" ", "-")}`} aria-label={`${score} out of 100, ${band}`}>
      <svg viewBox="0 0 100 100" aria-hidden="true">
        <circle className="ring-track" cx="50" cy="50" r="42" />
        <motion.circle
          className="ring-value"
          cx="50"
          cy="50"
          r="42"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: offset }}
          animate={{ strokeDashoffset: offset }}
          transition={{ duration: 1.1, ease: "easeOut" }}
        />
      </svg>
      <div className="ring-copy">
        <strong>{score}</strong>
        <span>/100</span>
      </div>
      <span className="ring-band">{band}</span>
    </div>
  );
}

function ProductPreview() {
  const report: ScanReport = demoReport;
  const findings = report.findings.slice(0, 3);
  const previewFinding = report.findings.find(
    (finding) => finding.fix?.validated,
  );
  const previewPatch =
    report.findings.find((finding) => finding.fix?.validated)?.fix?.patch ??
    "--- a/app/api/health/route.ts\n+++ b/app/api/health/route.ts\n+export function GET() {\n+  return Response.json({ status: 'ok' });\n+}";
  return (
    <Reveal className="preview-wrap">
      <div className="preview-halo" aria-hidden="true" />
      <div className="product-window">
        <div className="window-chrome">
          <div className="window-dots" aria-hidden="true">
            <i />
            <i />
            <i />
          </div>
          <div className="window-address">
            <LockKeyhole aria-hidden="true" /> prodcheck.dev/report/prodcheck-fixture/{report.repo.name}
          </div>
          <span className="window-live"><i /> Live report</span>
        </div>
        <div className="preview-report">
          <div className="preview-report-top">
            <div>
              <div className="preview-kicker">PRODUCTION READINESS REPORT</div>
              <div className="preview-repo">prodcheck-fixture/<b>{report.repo.name}</b></div>
              <div className="preview-commit">
                commit <code>{report.repo.commitSha.slice(0, 8)}</code> · scanned just now
              </div>
            </div>
            <span className="score-version">Score v{report.scoreVersion}</span>
          </div>
          <div className="preview-overview">
            <ScoreRing score={report.score} band={report.scoreBand} />
            <div className="preview-categories">
              {report.categoryBreakdown.map((category) => (
                <div className="mini-category" key={category.category}>
                  <div className="mini-category-label">
                    <span>{category.category}</span>
                    <b>{category.score}</b>
                  </div>
                  <div className="mini-track">
                    <motion.div
                      className="mini-value"
                      initial={{ width: `${category.score}%` }}
                      whileInView={{ width: `${category.score}%` }}
                      viewport={{ once: true }}
                    />
                  </div>
                </div>
              ))}
            </div>
            <div className="preview-findings-count">
              <strong>{report.findings.length}</strong>
              <span>findings</span>
            </div>
          </div>
          <div className="preview-body">
            <div className="preview-findings">
              <div className="preview-subhead">
                Findings <span>{report.findings.length}</span>
              </div>
              {findings.map((finding, index) => (
                <motion.div
                  className="preview-finding"
                  key={finding.id}
                  initial={{ x: -8 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.08 }}
                >
                  <span
                    className={`severity-dot severity-dot-${finding.severity}`}
                  />
                  <div>
                    <strong>{finding.title}</strong>
                    <code>{finding.checkId}</code>
                  </div>
                  <span className={`severity-text severity-text-${finding.severity}`}>
                    {finding.severity}
                  </span>
                </motion.div>
              ))}
            </div>
            <div className="preview-diff">
              <div className="preview-diff-top">
                <span><FileCode2 aria-hidden="true" /> Verified fix</span>
                <span className="verified-label"><Check aria-hidden="true" /> VALIDATED</span>
              </div>
              <div className="preview-file-path">
                {previewFinding?.fix?.description ?? "Add a health endpoint"}
              </div>
              <pre aria-label="Example verified patch">
                {previewPatch.split("\n").slice(0, 7).map((line, index) => (
                  <span
                    className={line.startsWith("+") ? "diff-add" : line.startsWith("-") ? "diff-remove" : ""}
                    key={`${index}-${line}`}
                  >
                    {line || " "}{"\n"}
                  </span>
                ))}
              </pre>
            </div>
          </div>
        </div>
      </div>
      <p className="preview-caption">
        Real scan output from the <code>{report.repo.name}</code> fixture ·
        deterministic score · verified patch
      </p>
    </Reveal>
  );
}

function Hero({
  props,
}: {
  props: Omit<RepositoryFieldProps, "id" | "compact">;
}) {
  return (
    <section className="hero-section shell" id="scan">
      <Reveal className="hero-copy">
        <div className="hero-pill"><span /> Open source <b>·</b> No login required</div>
        <h1>
          Ship with confidence.
          <br />
          <span>Know what to fix.</span>
        </h1>
        <p className="hero-subtitle">
          A clear, evidence-backed readiness check for the app you’re about to ship.
          Rules decide the score. You stay in control.
        </p>
        <RepositoryField id="repository-url" {...props} />
      </Reveal>
      <ProductPreview />
    </section>
  );
}

type RepositoryFieldProps = {
  url: string;
  onChange: (value: string) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  busy: boolean;
  error: string;
  progress?: ScanProgress;
  onExample: (repo: string) => void;
};

function ProofStrip() {
  const duration = (benchmark.medianScanTimeMs / 1000).toFixed(1);
  return (
    <section className="proof-section" id="benchmark">
      <div className="shell proof-inner">
        <p className="proof-heading">Benchmarked on real public repositories</p>
        <div className="stat-grid">
          <AnimatedStat value={benchmark.scanned} suffix="" label="repositories scanned" />
          <AnimatedStat value={benchmark.criticalFindingPercent} suffix="%" label="with critical findings" />
          <div className="stat-item">
            <div className="stat-value">{duration}<small>s</small></div>
            <div className="stat-label">median scan time</div>
          </div>
          <AnimatedStat value={benchmark.patchValidationRate} suffix="%" label="patch validation rate" />
        </div>
        <p className="benchmark-note">
          {benchmark.scanned} repositories in the current benchmark · source: <code>benchmarks/results.json</code>
        </p>
      </div>
    </section>
  );
}

function SectionHeading({
  kicker,
  title,
  description,
}: {
  kicker: string;
  title: string;
  description?: string;
}) {
  return (
    <div className="section-heading">
      <div className="section-kicker">{kicker}</div>
      <h2>{title}</h2>
      {description && <p>{description}</p>}
    </div>
  );
}

function HowItWorks() {
  return (
    <section className="section shell" id="how-it-works">
      <Reveal>
        <SectionHeading
          kicker="A clear path to launch"
          title="From repo URL to a better release."
          description="No setup. No black box. Just useful checks, grounded in your codebase."
        />
      </Reveal>
      <div className="steps-grid">
        {steps.map((step, index) => {
          const Icon = step.icon;
          return (
            <Reveal className="step-card surface-card" delay={index * 0.08} key={step.title}>
              <div className="step-topline"><span>0{index + 1}</span><ArrowUpRight aria-hidden="true" /></div>
              <div className="step-icon"><Icon aria-hidden="true" /></div>
              <h3>{step.title}</h3>
              <p>{step.text}</p>
              <div className="step-detail"><Terminal aria-hidden="true" /> {step.detail}</div>
            </Reveal>
          );
        })}
      </div>
    </section>
  );
}

function CheckCatalog() {
  return (
    <section className="section checks-section" id="checks">
      <div className="shell">
        <Reveal>
          <SectionHeading
            kicker="19 checks · 5 categories"
            title="The details that decide launch day."
            description="Focused on the security and reliability gaps that commonly ship in modern JavaScript apps."
          />
        </Reveal>
        <div className="category-grid">
          {categories.map((category, index) => {
            const Icon = category.icon;
            return (
              <Reveal className="category-card surface-card" delay={index * 0.06} key={category.name}>
                <div className="category-icon"><Icon aria-hidden="true" /></div>
                <div className="category-card-heading"><h3>{category.name}</h3><span>0{index + 1}</span></div>
                <p>{category.description}</p>
                <ul className="check-examples">
                  {category.checks.slice(0, 3).map(([id, title]) => (
                    <li key={id}><code>{id}</code><span>{title}</span></li>
                  ))}
                </ul>
                <details className="all-checks">
                  <summary>View all {category.checks.length} checks <ChevronDown aria-hidden="true" /></summary>
                  <ul>
                    {category.checks.map(([id, title]) => (
                      <li key={id}><code>{id}</code><span>{title}</span></li>
                    ))}
                  </ul>
                </details>
              </Reveal>
            );
          })}
        </div>
        <p className="catalog-footnote">
          Detection rules and known limitations are documented in <Link href="https://github.com">docs/CHECKS.md <ArrowUpRight aria-hidden="true" /></Link>.
        </p>
      </div>
    </section>
  );
}

function DecisionSection() {
  return (
    <section className="section shell">
      <Reveal className="decision-panel">
        <div className="decision-copy">
          <div className="section-kicker">A different kind of AI security tool</div>
          <h2>Rules decide.<br /><span>AI explains.</span></h2>
          <p>
            The score comes from versioned, testable rules. Optional AI can make findings easier to understand, but it cannot add a finding, alter your score, or approve a patch.
          </p>
          <div className="decision-points">
            <div><Check aria-hidden="true" /> Stable scores you can reproduce</div>
            <div><Check aria-hidden="true" /> Fixes validated by deterministic checks</div>
            <div><Check aria-hidden="true" /> Works fully without an AI key</div>
          </div>
        </div>
        <div className="flow-diagram" aria-label="Repository flows through deterministic checks to a score and validated fix; optional AI only rewrites explanations">
          <div className="flow-node"><GitBranch aria-hidden="true" /><span>Repository</span><small>read-only snapshot</small></div>
          <ArrowDownRight className="flow-arrow" aria-hidden="true" />
          <div className="flow-node flow-node-primary"><ShieldCheck aria-hidden="true" /><span>Rules engine</span><small>findings + score</small></div>
          <div className="flow-outputs">
            <div className="flow-output"><Check aria-hidden="true" /><span>Verified fixes</span></div>
            <div className="flow-output flow-output-ai"><Sparkles aria-hidden="true" /><span>Optional plain-English explanation</span></div>
          </div>
          <div className="flow-rule">AI has no path to the score or validator</div>
        </div>
      </Reveal>
    </section>
  );
}

function SampleReport() {
  const report: ScanReport = sampleReport;
  const candidate = report.findings.find((finding) => finding.fix?.validated) ?? report.findings[0];
  const [tab, setTab] = useState<"why" | "evidence" | "fix">("why");
  const [copied, setCopied] = useState(false);
  const patch = candidate.fix?.patch ?? "No automatic patch is available for this context.";
  async function copyPatch() {
    try {
      await navigator.clipboard.writeText(patch);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1600);
    } catch {
      setTab("fix");
    }
  }
  function downloadPatch() {
    const url = URL.createObjectURL(new Blob([patch], { type: "text/x-diff" }));
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${candidate.checkId.toLowerCase()}-fix.patch`;
    anchor.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return (
    <section className="section sample-section">
      <div className="shell sample-grid">
        <Reveal className="sample-copy">
          <div className="section-kicker">A report you can act on</div>
          <h2>Every finding comes with a reason, a location, and a next step.</h2>
          <p>Start with the impact. Inspect the evidence. Review the patch. Nothing is hidden behind a single number.</p>
          <div className="sample-assurances"><span><Check /> Source lines included</span><span><Check /> Patch gate shown</span></div>
        </Reveal>
        <Reveal className="sample-report surface-card">
          <div className="sample-report-head">
            <div className="sample-finding-code"><span className={`severity-dot severity-dot-${candidate.severity}`} /> {candidate.checkId} <i>·</i> {candidate.category}</div>
            <span className={`severity-pill severity-pill-${candidate.severity}`}>{candidate.severity}</span>
          </div>
          <h3>{candidate.title}</h3>
          <div className="finding-tabs" role="tablist" aria-label="Sample finding details">
            {([
              ["why", "Why it matters"],
              ["evidence", "Evidence"],
              ["fix", "Fix"],
            ] as const).map(([key, label]) => (
              <button
                className={tab === key ? "active" : ""}
                type="button"
                role="tab"
                id={`sample-tab-${key}`}
                aria-selected={tab === key}
                aria-controls="sample-finding-panel"
                tabIndex={tab === key ? 0 : -1}
                key={key}
                onClick={() => setTab(key)}
                onKeyDown={(event) => {
                  if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
                  event.preventDefault();
                  const allTabs = Array.from(
                    event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>(
                      '[role="tab"]',
                    ) ?? [],
                  );
                  const currentIndex = allTabs.indexOf(event.currentTarget);
                  const direction = event.key === "ArrowRight" ? 1 : -1;
                  allTabs[(currentIndex + direction + allTabs.length) % allTabs.length]?.click();
                  allTabs[(currentIndex + direction + allTabs.length) % allTabs.length]?.focus();
                }}
              >{label}</button>
            ))}
          </div>
          <AnimatePresence mode="wait">
            <motion.div
              className="sample-tab-panel"
              key={tab}
              role="tabpanel"
              id="sample-finding-panel"
              aria-labelledby={`sample-tab-${tab}`}
              initial={{ opacity: 1, y: 5 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -4 }}
              transition={{ duration: 0.16 }}
            >
              {tab === "why" && <p>{candidate.explanation}</p>}
              {tab === "evidence" && (
                <div className="sample-evidence">
                  {candidate.evidence.length ? candidate.evidence.slice(0, 2).map((item) => (
                    <div key={`${item.file}:${item.lineStart}`}>
                      <code>{item.file}:{item.lineStart}</code>
                      <pre>{item.snippet || "No source snippet available."}</pre>
                    </div>
                  )) : <p>No source location was needed for this repository-level finding.</p>}
                </div>
              )}
              {tab === "fix" && (
                <div className="sample-fix">
                  <div className="fix-description"><Check aria-hidden="true" /> {candidate.fix?.description ?? "A verified patch is not available for this finding."}</div>
                  <pre aria-label={`Patch for ${candidate.title}`}>
                    {patch.split("\n").map((line, index) => <span className={line.startsWith("+") ? "diff-add" : line.startsWith("-") ? "diff-remove" : ""} key={`${index}-${line}`}>{line || " "}{"\n"}</span>)}
                  </pre>
                </div>
              )}
            </motion.div>
          </AnimatePresence>
          <div className="sample-report-actions">
            <span className={candidate.fix?.validated ? "verified-label" : "suggested-label"}>
              {candidate.fix?.validated ? <Check aria-hidden="true" /> : <Sparkles aria-hidden="true" />}
              {candidate.fix?.validated ? "Verified fix" : "Review required"}
            </span>
            <div>
              <button type="button" className="text-action" onClick={() => void copyPatch()}><Clipboard aria-hidden="true" /> {copied ? "Copied" : "Copy patch"}</button>
              <button type="button" className="text-action" onClick={downloadPatch}><ArrowDownRight aria-hidden="true" /> Download</button>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

function FAQ() {
  return (
    <section className="section shell faq-section" id="faq">
      <Reveal>
        <SectionHeading kicker="Good questions" title="Before you ship it." description="A few things teams usually want to know first." />
      </Reveal>
      <div className="faq-list">
        {faqs.map((faq, index) => (
          <Reveal delay={index * 0.035} key={faq.question}>
            <details className="faq-item">
              <summary>{faq.question}<ChevronDown aria-hidden="true" /></summary>
              <p>{faq.answer}</p>
            </details>
          </Reveal>
        ))}
      </div>
    </section>
  );
}

function Footer({ onThemeToggle, light }: { onThemeToggle: () => void; light: boolean }) {
  return (
    <footer className="site-footer">
      <div className="shell footer-main">
        <div className="footer-brand-block">
          <Brand />
          <p>Production readiness, with receipts.</p>
          <div className="footer-version"><span /> Scanner 0.0.0 <i>·</i> score v1</div>
        </div>
        <div className="footer-column"><h3>Product</h3><a href="#checks">Checks</a><a href="#how-it-works">How it works</a><a href="#benchmark">Benchmark</a></div>
        <div className="footer-column"><h3>Docs</h3><a href="https://github.com">Scoring model <ArrowUpRight /></a><a href="https://github.com">Check catalog <ArrowUpRight /></a><a href="https://github.com">Limitations <ArrowUpRight /></a></div>
        <div className="footer-column"><h3>Trust</h3><a href="https://github.com">GitHub <ArrowUpRight /></a><a href="https://github.com">Security <ArrowUpRight /></a><button type="button" className="footer-theme" onClick={onThemeToggle}>{light ? <Moon /> : <Sun />} Theme</button></div>
      </div>
      <div className="shell footer-bottom"><span>© 2026 ProdCheck. Open source and built for careful shipping.</span><span>Scanned repositories are never executed.</span></div>
    </footer>
  );
}

export function MarketingPage({
  url,
  onChange,
  onSubmit,
  onStart,
  busy,
  error,
  progress,
  light,
  onThemeToggle,
}: {
  url: string;
  onChange: (value: string) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  onStart: (repository: string) => void;
  busy: boolean;
  error: string;
  progress?: ScanProgress;
  light: boolean;
  onThemeToggle: () => void;
}) {
  const repositoryFieldProps = {
    url,
    onChange,
    onSubmit,
    busy,
    error,
    progress,
    onExample: (repository: string) => {
      onChange(`https://github.com/${repository}`);
      onStart(`https://github.com/${repository}`);
    },
  };
  return (
    <>
      <Header light={light} onToggle={onThemeToggle} />
      <main>
        <div className="hero-backdrop" aria-hidden="true" />
        <Hero props={repositoryFieldProps} />
        <ProofStrip />
        <HowItWorks />
        <CheckCatalog />
        <DecisionSection />
        <SampleReport />
        <FAQ />
        <section className="final-cta shell" id="final-scan">
          <Reveal className="final-cta-inner">
            <div className="final-cta-icon"><Workflow aria-hidden="true" /></div>
            <div className="section-kicker">Make the next release the easy one</div>
            <h2>See what your repo is telling you.</h2>
            <p>Get a deterministic score, findings you can verify, and a safe next step.</p>
            <RepositoryField id="repository-url-footer" {...repositoryFieldProps} compact />
          </Reveal>
        </section>
      </main>
      <Footer light={light} onThemeToggle={onThemeToggle} />
    </>
  );
}
